FROM node:20-slim AS build

WORKDIR /app

ENV NODE_OPTIONS="--max-old-space-size=512"

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

RUN npx ng build --configuration=dev

FROM nginx:alpine

COPY --from=build /app/dist/front /usr/share/nginx/html

RUN echo 'server { \
    listen 80; \
    root /usr/share/nginx/html; \
    index index.html; \
    location / { \
        try_files $uri $uri/ /index.html; \
    } \
}' > /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
